"""
Pre-generates the Excel dashboard with realistic mock AI output.
Run this to get the demo dashboard without needing an API key.
"""
import pandas as pd
import sys
sys.path.insert(0, '.')

# Mock classification data — mirrors exactly what Claude API would return
classifications = [
    {"ticket_id":"10001","issue_type":"Account Access","urgency":"High","sentiment":"Frustrated","can_be_automated":True,"recommended_macro":"Trigger Password Reset Email","one_line_summary":"User locked out due to invalid credentials — password reset needed.","estimated_handle_time_mins":3},
    {"ticket_id":"10002","issue_type":"Billing & Payments","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Unauthorized Transaction Investigation","one_line_summary":"Unauthorized $500 withdrawal reported — requires fraud team review.","estimated_handle_time_mins":20},
    {"ticket_id":"10003","issue_type":"Product Education","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Send FHSA How-To Guide","one_line_summary":"New user asking how to open an FHSA — send onboarding guide.","estimated_handle_time_mins":2},
    {"ticket_id":"10004","issue_type":"Technical Bug","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"iOS Crash Report + Engineering Ticket","one_line_summary":"App crashing on iPhone 14/iOS 17.2 — escalate to engineering.","estimated_handle_time_mins":10},
    {"ticket_id":"10005","issue_type":"Account Access","urgency":"Medium","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Resend Verification Email","one_line_summary":"Verification email not received after 3 days — resend flow.","estimated_handle_time_mins":2},
    {"ticket_id":"10006","issue_type":"Billing & Payments","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Duplicate Charge Refund Process","one_line_summary":"Duplicate $9.99 subscription charge — initiate refund review.","estimated_handle_time_mins":8},
    {"ticket_id":"10007","issue_type":"KYC & Compliance","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"TFSA Contribution Room Audit","one_line_summary":"TFSA over-contribution flag — manual account audit required.","estimated_handle_time_mins":12},
    {"ticket_id":"10008","issue_type":"Account Access","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"2FA Recovery with Identity Verification","one_line_summary":"2FA broken after new phone — requires ID verification to recover.","estimated_handle_time_mins":10},
    {"ticket_id":"10009","issue_type":"Product Education","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Send RRSP Transfer Guide","one_line_summary":"User wants to transfer RRSP from TD — send standard process guide.","estimated_handle_time_mins":2},
    {"ticket_id":"10010","issue_type":"Portfolio & Trading","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Portfolio Display Bug Escalation","one_line_summary":"Completed trade not reflecting in portfolio — platform display bug.","estimated_handle_time_mins":8},
    {"ticket_id":"10011","issue_type":"Billing & Payments","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Unauthorized Premium Charge Reversal","one_line_summary":"Unauthorized Premium subscription charge — immediate refund required.","estimated_handle_time_mins":15},
    {"ticket_id":"10012","issue_type":"KYC & Compliance","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Escalate T5 Slip Generation","one_line_summary":"T5 tax slip missing ahead of filing deadline — compliance escalation.","estimated_handle_time_mins":12},
    {"ticket_id":"10013","issue_type":"Product Education","urgency":"Low","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Send RRSP Beneficiary Guide","one_line_summary":"User asking how to add RRSP beneficiary — send help article.","estimated_handle_time_mins":2},
    {"ticket_id":"10014","issue_type":"Billing & Payments","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Investigate Pending Deposit","one_line_summary":"$1,200 deposit pending 5 days — investigate banking partner delay.","estimated_handle_time_mins":10},
    {"ticket_id":"10015","issue_type":"Technical Bug","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Flag Currency Display Bug to Engineering","one_line_summary":"USD holdings displaying without currency label — UI display bug.","estimated_handle_time_mins":5},
    {"ticket_id":"10016","issue_type":"Product Education","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Send MER & Fee Schedule","one_line_summary":"Prospective user asking about ETF MER fees — send fee schedule.","estimated_handle_time_mins":2},
    {"ticket_id":"10017","issue_type":"KYC & Compliance","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Urgent Account Unfreeze Review","one_line_summary":"Account frozen with imminent bill payment — urgent compliance review.","estimated_handle_time_mins":20},
    {"ticket_id":"10018","issue_type":"Account Access","urgency":"Medium","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Security Question Reset Flow","one_line_summary":"Forgotten security questions — send reset flow instructions.","estimated_handle_time_mins":3},
    {"ticket_id":"10019","issue_type":"Portfolio & Trading","urgency":"High","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Trade Execution Delay Investigation","one_line_summary":"40-minute market order delay causing financial loss — requires review.","estimated_handle_time_mins":15},
    {"ticket_id":"10020","issue_type":"Product Education","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Send Auto-Invest Setup Guide","one_line_summary":"New user wants to set up recurring TFSA deposits — send guide.","estimated_handle_time_mins":2},
    {"ticket_id":"10021","issue_type":"KYC & Compliance","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Manual SIN Verification Review","one_line_summary":"SIN rejected during KYC despite being valid — manual review needed.","estimated_handle_time_mins":10},
    {"ticket_id":"10022","issue_type":"Billing & Payments","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Referral Bonus Audit","one_line_summary":"Referral bonus not applied after 3 months — investigate eligibility.","estimated_handle_time_mins":8},
    {"ticket_id":"10023","issue_type":"Product Education","urgency":"Low","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Explain Fractional Shares","one_line_summary":"User confused by fractional share amount — send education article.","estimated_handle_time_mins":2},
    {"ticket_id":"10024","issue_type":"KYC & Compliance","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Manual ID Verification Escalation","one_line_summary":"Driver's license failing automated verification 4 times — manual review.","estimated_handle_time_mins":12},
    {"ticket_id":"10025","issue_type":"KYC & Compliance","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Generate RRSP Contribution Receipt","one_line_summary":"RRSP contribution receipt not generated — trigger document creation.","estimated_handle_time_mins":8},
    {"ticket_id":"10026","issue_type":"Security","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Emergency Account Lockdown & Security Review","one_line_summary":"Account compromised — email changed by unauthorized user. URGENT.","estimated_handle_time_mins":20},
    {"ticket_id":"10027","issue_type":"Portfolio & Trading","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Investigate Missing Dividend Credit","one_line_summary":"Expected dividend from RY not credited — investigate payment clearing.","estimated_handle_time_mins":8},
    {"ticket_id":"10028","issue_type":"Technical Bug","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Address Update Bug Report","one_line_summary":"Profile address not saving after update — platform bug report.","estimated_handle_time_mins":5},
    {"ticket_id":"10029","issue_type":"Billing & Payments","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Premium Feature Activation Review","one_line_summary":"Premium features inaccessible after paid upgrade — check provisioning.","estimated_handle_time_mins":8},
    {"ticket_id":"10030","issue_type":"Product Education","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Send Managed Portfolio Overview","one_line_summary":"New user asking how managed investing works — send onboarding article.","estimated_handle_time_mins":2},
    {"ticket_id":"10031","issue_type":"Billing & Payments","urgency":"High","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Cash Card Decline Investigation","one_line_summary":"Wealthsimple Cash card declined with positive balance — investigate.","estimated_handle_time_mins":10},
    {"ticket_id":"10032","issue_type":"Account Access","urgency":"Medium","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Send Account Closure Instructions","one_line_summary":"User wants to close account — send self-serve closure guide.","estimated_handle_time_mins":3},
    {"ticket_id":"10033","issue_type":"Technical Bug","urgency":"Low","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Android Notification Bug Report","one_line_summary":"Push notifications not working on Android — log bug report.","estimated_handle_time_mins":5},
    {"ticket_id":"10034","issue_type":"Account Access","urgency":"Medium","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Send Withdrawal Limit Increase Instructions","one_line_summary":"User hit daily withdrawal limit — send limit increase request guide.","estimated_handle_time_mins":3},
    {"ticket_id":"10035","issue_type":"Billing & Payments","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"ACH Failure & Negative Balance Resolution","one_line_summary":"ACH transfer rejected creating negative balance — urgent resolution.","estimated_handle_time_mins":18},
    {"ticket_id":"10036","issue_type":"Technical Bug","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Documents Section Bug Escalation","one_line_summary":"Documents section empty — statements not loading — engineering bug.","estimated_handle_time_mins":5},
    {"ticket_id":"10037","issue_type":"Product Education","urgency":"Low","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Send CIPF/CDIC Insurance Guide","one_line_summary":"User asking about deposit insurance — send protection explainer.","estimated_handle_time_mins":2},
    {"ticket_id":"10038","issue_type":"Account Access","urgency":"High","sentiment":"Frustrated","can_be_automated":True,"recommended_macro":"Trigger Account Unlock + Password Reset","one_line_summary":"Account locked after failed login attempts — trigger unlock flow.","estimated_handle_time_mins":3},
    {"ticket_id":"10039","issue_type":"KYC & Compliance","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Correct RRSP Receipt Tax Year","one_line_summary":"RRSP receipt shows wrong tax year — will impact filing — fix urgently.","estimated_handle_time_mins":12},
    {"ticket_id":"10040","issue_type":"Portfolio & Trading","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Explain Limit Order Mechanics","one_line_summary":"Limit order not filling — explain limit vs market order behaviour.","estimated_handle_time_mins":6},
    {"ticket_id":"10041","issue_type":"Product Education","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Send DCA Strategy Guide","one_line_summary":"User asking about dollar-cost averaging — send educational guide.","estimated_handle_time_mins":2},
    {"ticket_id":"10042","issue_type":"Technical Bug","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Portfolio Risk Setting Bug Report","one_line_summary":"Risk level reverting after save — UI settings bug — log report.","estimated_handle_time_mins":5},
    {"ticket_id":"10043","issue_type":"KYC & Compliance","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Duplicate Account Merge Process","one_line_summary":"Duplicate account created — requires compliance review to merge.","estimated_handle_time_mins":15},
    {"ticket_id":"10044","issue_type":"Billing & Payments","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Internal Transfer Error Investigation","one_line_summary":"TFSA to personal account transfer failing — investigate payment flow.","estimated_handle_time_mins":10},
    {"ticket_id":"10045","issue_type":"Technical Bug","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Crypto Section Outage Report","one_line_summary":"Crypto tab showing infinite spinner for 2 days — platform issue.","estimated_handle_time_mins":5},
    {"ticket_id":"10046","issue_type":"KYC & Compliance","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Options Approval Status Update","one_line_summary":"Options trading application pending 2 weeks — send status update.","estimated_handle_time_mins":6},
    {"ticket_id":"10047","issue_type":"KYC & Compliance","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Capital Gains Report Correction","one_line_summary":"Incorrect capital gains showing profit on a loss — tax compliance error.","estimated_handle_time_mins":20},
    {"ticket_id":"10048","issue_type":"Technical Bug","urgency":"Low","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Price Alert Bug Report","one_line_summary":"Price alert not triggering when target hit — log notification bug.","estimated_handle_time_mins":4},
    {"ticket_id":"10049","issue_type":"Account Access","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Manual Bank Link Escalation","one_line_summary":"RBC bank link failing at final step repeatedly — escalate to partner.","estimated_handle_time_mins":12},
    {"ticket_id":"10050","issue_type":"Billing & Payments","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Misdirected Withdrawal Recovery","one_line_summary":"Withdrawal sent to closed bank account — initiate fund recovery.","estimated_handle_time_mins":20},
    {"ticket_id":"10051","issue_type":"Product Education","urgency":"Low","sentiment":"Frustrated","can_be_automated":True,"recommended_macro":"Send Market Volatility Explainer","one_line_summary":"User alarmed by 12% portfolio drop — send market context guide.","estimated_handle_time_mins":2},
    {"ticket_id":"10052","issue_type":"Account Access","urgency":"Medium","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Account Lookup by Phone/SIN Flow","one_line_summary":"User forgot signup email — send account recovery lookup instructions.","estimated_handle_time_mins":3},
    {"ticket_id":"10053","issue_type":"Technical Bug","urgency":"Low","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Spare Change Feature Bug Report","one_line_summary":"Round-up feature stopped triggering on recent purchases — bug report.","estimated_handle_time_mins":4},
    {"ticket_id":"10054","issue_type":"Product Education","urgency":"Low","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Send FHSA Contribution Limit Guide","one_line_summary":"User asking 2024 FHSA annual limit — send contribution guide.","estimated_handle_time_mins":2},
    {"ticket_id":"10055","issue_type":"Product Education","urgency":"Low","sentiment":"Neutral","can_be_automated":True,"recommended_macro":"Send Cash Account Interest Rate","one_line_summary":"User asking current Cash account interest rate — send rate info.","estimated_handle_time_mins":2},
    {"ticket_id":"10056","issue_type":"Portfolio & Trading","urgency":"Critical","sentiment":"Angry","can_be_automated":False,"recommended_macro":"Missing Stop-Loss Order Investigation","one_line_summary":"Stop-loss order disappeared with position still open — urgent review.","estimated_handle_time_mins":20},
    {"ticket_id":"10057","issue_type":"KYC & Compliance","urgency":"Medium","sentiment":"Neutral","can_be_automated":False,"recommended_macro":"Legal Name Change Process","one_line_summary":"User needs legal name change after marriage — KYC update required.","estimated_handle_time_mins":8},
    {"ticket_id":"10058","issue_type":"Feature Request","urgency":"Low","sentiment":"Positive","can_be_automated":True,"recommended_macro":"Log Feature Request + Send Acknowledgement","one_line_summary":"User requesting choice of account for round-up deposits — log feedback.","estimated_handle_time_mins":2},
    {"ticket_id":"10059","issue_type":"Technical Bug","urgency":"High","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Cross-Account Display Bug Escalation","one_line_summary":"Trade and personal accounts showing identical holdings — critical UI bug.","estimated_handle_time_mins":10},
    {"ticket_id":"10060","issue_type":"Technical Bug","urgency":"Medium","sentiment":"Frustrated","can_be_automated":False,"recommended_macro":"Statement Download Bug Report","one_line_summary":"Statement download refreshes page instead of downloading — bug report.","estimated_handle_time_mins":5},
]

import csv, pandas as pd

# Load original tickets
with open("mock_tickets.csv", newline="", encoding="utf-8") as f:
    tickets = list(csv.DictReader(f))

ticket_map = {t["ticket_id"]: t for t in tickets}
results = []
for c in classifications:
    base = ticket_map.get(str(c["ticket_id"]), {})
    results.append({**base, **c})

df = pd.DataFrame(results)
df.to_csv("triage_output.csv", index=False)
print(f"✅ Demo output CSV saved with {len(df)} classified tickets.")

# Build the dashboard using same function from triage_agent
from triage_agent import build_dashboard, print_summary
build_dashboard(df)
print_summary(df)
print("\n✅ triage_dashboard.xlsx created — ready to present.")
